idf_component_register(
    SRCS
        "app_main.cpp" 
        "libs/provision/provision.cpp"
        "libs/display/blink.cpp" 
        "libs/deepsleep.cpp"
        "libs/sensors/bme680.cpp"
        "libs/sensors/bh1750.cpp"
        "libs/sensors/adc.cpp"
        "libs/utils/utils.cpp" 
        "libs/utils/kvs.cpp"
        #-----------------
        "libs/test/tst_utils.cpp"
       
    INCLUDE_DIRS
        "."
        "libs"
    REQUIRES
        nvs_flash 
        wifi_provisioning 
        json 
        esp_wifi 
        mqtt 
        driver 
        spi_flash
        unity
        esp_http_server
        bme680
        bh1750
    )
