idf_component_register(
    SRCS
        "app_main.cpp" 
        "mqtt/mqtt_wrapper.cpp" 
        "provision.cpp"
        "blink.cpp" 
        "deepsleep.cpp"
        "sensors/bme680.cpp"
        "sensors/bh1750.cpp"
        "sensors/adc.cpp"
        "utils/utils.cpp" 
        "utils/kvs.cpp"
        #-----------------
        "test/tst_utils.cpp"
       
    INCLUDE_DIRS
        "." 
    REQUIRES
        nvs_flash 
        wifi_provisioning 
        json 
        esp_wifi 
        mqtt 
        driver 
        spi_flash
        unity
        esp_http_server
        bme680
        bh1750
    )
